#pragma once

#define Version_Error_Message       "The current procedure has come to a stop because auto-setup is not support for this version of CC / iClone. Please update to the appropriate version."
#define Version_Not_Suitable        "Auto-setup is not support for this version of CC / iClone and some issues may occur as a result. Please update to the appropriate version."


// Bone Names
TArray<FString> CCBoneConvertedNames =
{
    "clavicle_l",
    "upperarm_l",
    "lowerarm_l",
    "lowerarm_twist_01_l",
    "hand_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "thigh_l",
    "calf_l",
    "foot_l",
    "ball_l",
    "clavicle_r",
    "upperarm_r",
    "lowerarm_r",
    "lowerarm_twist_01_r",
    "hand_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "thigh_r",
    "calf_r",
    "foot_r",
    "ball_r",
    "head",
    "neck_01",
    "spine_03",
    "spine_02",
    "spine_01",
    "pelvis",
    "root",
    "upperarm_twist_01_r",
    "thigh_twist_01_r",
    "calf_twist_01_r",
    "upperarm_twist_01_l",
    "thigh_twist_01_l",
    "calf_twist_01_l"
};
